# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uecaps.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cuecaps.proto\"\x12\n\x01\x61\x12\r\n\x01\x61\x18\x03 \x03(\x0b\x32\x02.b\"\x12\n\x01\x62\x12\r\n\x01\x62\x18\x02 \x03(\x0b\x32\x02.c\"\x13\n\x01\x63\x12\x0e\n\x01\x63\x18\x01 \x03(\x0b\x32\x03.ca\"F\n\x02\x63\x61\x12\x0c\n\x04\x62\x61nd\x18\x01 \x02(\x05\x12\x0c\n\x04\x64lcc\x18\x02 \x02(\x05\x12\x0c\n\x04ulcc\x18\x03 \x02(\x05\x12\n\n\x02\x64l\x18\x06 \x02(\x0c\x12\n\n\x02ul\x18\x07 \x01(\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uecaps_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _A._serialized_start=16
  _A._serialized_end=34
  _B._serialized_start=36
  _B._serialized_end=54
  _C._serialized_start=56
  _C._serialized_end=75
  _CA._serialized_start=77
  _CA._serialized_end=147
# @@protoc_insertion_point(module_scope)
