# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uecaps.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cuecaps.proto\"<\n\x01\x61\x12\r\n\x01\x61\x18\x03 \x03(\x0b\x32\x02.b\x12\x13\n\x04\x61\x61\x66s\x18\x06 \x03(\x0b\x32\x05.bafs\x12\x13\n\x04\x61\x62\x66s\x18\x07 \x03(\x0b\x32\x05.bbfs\"E\n\x04\x62\x61\x66s\x12\n\n\x02\x62w\x18\x03 \x01(\x05\x12\r\n\x05layer\x18\x02 \x01(\x05\x12\n\n\x02\x62\x61\x18\x01 \x01(\x05\x12\n\n\x02\x62\x62\x18\x04 \x01(\x05\x12\n\n\x02\x62\x63\x18\x05 \x01(\x05\"E\n\x04\x62\x62\x66s\x12\n\n\x02\x62w\x18\x03 \x01(\x05\x12\r\n\x05layer\x18\x02 \x01(\x05\x12\n\n\x02\x62\x61\x18\x01 \x01(\x05\x12\n\n\x02\x62\x62\x18\x04 \x01(\x05\x12\n\n\x02\x62\x63\x18\x05 \x01(\x05\"\x12\n\x01\x62\x12\r\n\x01\x62\x18\x02 \x03(\x0b\x32\x02.c\"\x13\n\x01\x63\x12\x0e\n\x01\x63\x18\x01 \x03(\x0b\x32\x03.ca\"R\n\x02\x63\x61\x12\x0c\n\x04\x62\x61nd\x18\x01 \x01(\x05\x12\x0c\n\x04\x64lcc\x18\x02 \x01(\x05\x12\x0c\n\x04ulcc\x18\x03 \x01(\x05\x12\x10\n\x04\x66sdl\x18\x06 \x03(\x05\x42\x02\x10\x01\x12\x10\n\x04\x66sul\x18\x07 \x03(\x05\x42\x02\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uecaps_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CA.fields_by_name['fsdl']._options = None
  _CA.fields_by_name['fsdl']._serialized_options = b'\020\001'
  _CA.fields_by_name['fsul']._options = None
  _CA.fields_by_name['fsul']._serialized_options = b'\020\001'
  _A._serialized_start=16
  _A._serialized_end=76
  _BAFS._serialized_start=78
  _BAFS._serialized_end=147
  _BBFS._serialized_start=149
  _BBFS._serialized_end=218
  _B._serialized_start=220
  _B._serialized_end=238
  _C._serialized_start=240
  _C._serialized_end=259
  _CA._serialized_start=261
  _CA._serialized_end=343
# @@protoc_insertion_point(module_scope)
